services:

  db:
    image: postgres:16-alpine
    container_name: calcfit-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: calcfit-app
    restart: unless-stopped

    build: .

    ports:
      - "8060:8060"

    environment:
      SPRING_PROFILES_ACTIVE: prod

      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TTL_SECONDS: ${JWT_ACCESS_TTL_SECONDS}
      JWT_REFRESH_TTL_SECONDS: ${JWT_REFRESH_TTL_SECONDS}

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: